<?php

declare(strict_types=1);

return [

    'patterns' => [
        '*' => '/(^[၁-၉]|^[1-9]|1[1-4]|၁[၁-၄])(\s*\/\s*|\s*|\s*\-\s*)([က-အa-zA-Z]+)(\s*[\[\(]\s*|\s*|\s*\{\s*)(ပြု|နိုင်|Naing|N|Pyu|P)(\s*[\]\)]\s*|\s*|\s*\}\s*)([၀-၉0-9]{5,6})/iu',

        'en' => '/(\b[1-9]|1[0-4]\b)(\s*\/\s*|\s*|\s*\-\s*)([A-Za-z]+)(\s*[\[\(]\s*|\s*|\s*\{\s*)(Naing|N|Pyu|P)(\s*[\]\)]\s*|\s*|\s*\}\s*)([\d]{5,6})/iu',

        'mm' => '/(\b[၁-၉]|၁[၁-၄])(\s*\/\s*|\s*|\s*\-\s*)([က-အ]+)(\s*[\[\(]\s*|\s*|\s*\{\s*)(ပြု|နိုင်)(\s*[\]\)]\s*|\s*|\s*\}\s*)([၀-၉]{5,6})/iu',
    ],

    'numbers' => [
        '၀' => '0',
        '၁' => '1',
        '၂' => '2',
        '၃' => '3',
        '၄' => '4',
        '၅' => '5',
        '၆' => '6',
        '၇' => '7',
        '၈' => '8',
        '၉' => '9',
    ],

    'types' => [
        ['mm' => 'နိုင်', 'en' => 'Naing'],
        ['mm' => 'ပြု', 'en' => 'Pyu'],
        ['mm' => 'နိုင်', 'en' => 'N'],
        ['mm' => 'ပြု', 'en' => 'P'],
    ],

    'states_and_divisions' => [
        'mm' => [
            '၁' => 'ကချင် ပြည်နယ်',
            '၂' => 'ကယား ပြည်နယ်',
            '၃' => 'ကရင် ပြည်နယ်',
            '၄' => 'ချင်း ပြည်နယ်',
            '၅' => 'စစ်ကိုင်း တိုင်းဒေသကြီး',
            '၆' => 'တနလာရီ တိုင်းဒေသကြီး',
            '၇' => 'ပဲခူး တိုင်းဒေသကြီး',
            '၈' => 'မကွေး တိုင်းဒေသကြီး',
            '၉' => 'မန္တလေး တိုင်းဒေသကြီး',
            '၉' => 'နေပြည်တော် ပြည်ထောင်စုနယ်မြေ',
            '၁၀' => 'မွန် ပြည်နယ်',
            '၁၁' => 'ရခိုင် ပြည်နယ်',
            '၁၂' => 'ရန်ကုန် တိုင်းဒေသကြီး',
            '၁၃' => 'ရှမ်း ပြည်နယ်',
            '၁၄' => 'ဧရာ၀တီ တိုင်းဒေသကြီး',
        ],

        'en' => [
            '1' => 'Kachin State',
            '2' => 'Kayah State',
            '3' => 'Kayin State',
            '4' => 'Chin State',
            '5' => 'Sagaing Region',
            '6' => 'Tanintharyi Region',
            '7' => 'Bago Region',
            '8' => 'Magway Region',
            '9' => 'Mandalay Region',
            '9' => 'NayPyiTaw Region',
            '10' => 'Mon State',
            '11' => 'Rakhine State',
            '12' => 'Yangon Region',
            '13' => 'Shan State',
            '14' => 'Ayeyarwady Region',
        ],
    ],

    'townships_codes' => [
        ['en' => 'WaMaNa', 'mm' => 'ဝမန'],
        ['en' => 'KaKaKa', 'mm' => 'ကကက'],
        ['en' => 'HsaDaNa', 'mm' => 'ဆဒန'],
        ['en' => 'AGaYa', 'mm' => 'အဂယ'],
        ['en' => 'TaNaNa', 'mm' => 'တနန'],
        ['en' => 'KaKhaKa', 'mm' => 'ကခက'],
        ['en' => 'RaBaYa', 'mm' => 'ရဗယ'],
        ['en' => 'KhaPhaNa', 'mm' => 'ခဖန'],
        ['en' => 'HsaLaNa', 'mm' => 'ဆလန'],
        ['en' => 'KaPaTa', 'mm' => 'ကပတ'],
        ['en' => 'PaWaNa', 'mm' => 'ပဝန'],
        ['en' => 'MaNyaNa', 'mm' => 'မညန'],
        ['en' => 'HaPaNa', 'mm' => 'ဟပန'],
        ['en' => 'MaKaTa', 'mm' => 'မကတ'],
        ['en' => 'HaTaNa', 'mm' => 'ဟတန'],
        ['en' => 'KaMaNa', 'mm' => 'ကမန'],
        ['en' => 'HpaKaNa', 'mm' => 'ဖကန'],
        ['en' => 'KaMaTa', 'mm' => 'ကမတ'],
        ['en' => 'BaMaNa', 'mm' => 'ဗမန'],
        ['en' => 'ThaLaHta', 'mm' => 'သလထ'],
        ['en' => 'ThaKhaNa', 'mm' => 'သခန'],
        ['en' => 'BaHaNa', 'mm' => 'ဗဟန'],
        ['en' => 'RaKaNa', 'mm' => 'ရကန'],
        ['en' => 'MaLaNa', 'mm' => 'မလန'],
        ['en' => 'MaMaNa', 'mm' => 'မမန'],
        ['en' => 'LaGaNa', 'mm' => 'လဂန'],
        ['en' => 'DaHpaYa', 'mm' => 'ဒဖယ'],
        ['en' => 'MaGaTa', 'mm' => 'မဂတ'],
        ['en' => 'BaTaHta', 'mm' => 'ဗတထ'],
        ['en' => 'MaSaNa', 'mm' => 'မစန'],
        ['en' => 'PaTaA', 'mm' => 'ပတအ'],
        ['en' => 'MaKhaBa', 'mm' => 'မခဘ'],
        ['en' => 'NaMaNa', 'mm' => 'နမန'],
        ['en' => 'PaNaDa', 'mm' => 'ပနဒ'],
        ['en' => 'KhaBaDa', 'mm' => 'ခဘဒ'],
        ['en' => 'KhaLaHpa', 'mm' => 'ခလဖ'],
        ['en' => 'HsaPaBa', 'mm' => 'ဆပဘ'],
        ['en' => 'HsaKaNa', 'mm' => 'ဆကန'],
        ['en' => 'LaKaNa', 'mm' => 'လကန'],
        ['en' => 'DaMaHsa', 'mm' => 'ဒမဆ'],
        ['en' => 'HpaRaHsa', 'mm' => 'ဖရဆ'],
        ['en' => 'RaTaNa', 'mm' => 'ရတန'],
        ['en' => 'BaLaKha', 'mm' => 'ဘလခ'],
        ['en' => 'HpaHsaNa', 'mm' => 'ဖဆန'],
        ['en' => 'RaThaNa', 'mm' => 'ရသန'],
        ['en' => 'BaANa', 'mm' => 'ဘအန'],
        ['en' => 'KhaRaNa', 'mm' => 'ခရန'],
        ['en' => 'SaKhaNa', 'mm' => 'စခန'],
        ['en' => 'LaBaNa', 'mm' => 'လဘန'],
        ['en' => 'KhaNaTa', 'mm' => 'ခနတ'],
        ['en' => 'ThaGhaKa', 'mm' => 'သဃက'],
        ['en' => 'PaKaNa', 'mm' => 'ပကန'],
        ['en' => 'RaRaTha', 'mm' => 'ရရသ'],
        ['en' => 'ThaTaKa', 'mm' => 'သတက'],
        ['en' => 'ThaTaNa', 'mm' => 'သတန'],
        ['en' => 'MaRaKa', 'mm' => 'မရက'],
        ['en' => 'LaThaNa', 'mm' => 'လသန'],
        ['en' => 'ThaKaTa', 'mm' => 'သကတ'],
        ['en' => 'BaGaLa', 'mm' => 'ဘဂလ'],
        ['en' => 'HpaPaNa', 'mm' => 'ဖပန'],
        ['en' => 'KaMaMa', 'mm' => 'ကမမ'],
        ['en' => 'KaKaRa', 'mm' => 'ကကရ'],
        ['en' => 'KaHsaKa', 'mm' => 'ကဆက'],
        ['en' => 'KhaMaTa', 'mm' => 'ခမသ'],
        ['en' => 'ThaLaNa', 'mm' => 'သလန'],
        ['en' => 'PaZaTa', 'mm' => 'ပဇတ'],
        ['en' => 'DaGaMa', 'mm' => 'ဒဂမ'],
        ['en' => 'ASaNa', 'mm' => 'အစန'],
        ['en' => 'KaDaNa', 'mm' => 'ကဒန'],
        ['en' => 'BaThaHsa', 'mm' => 'ဘသဆ'],
        ['en' => 'LaMaTa', 'mm' => 'လမတ'],
        ['en' => 'MaWaTa', 'mm' => 'မဝတ'],
        ['en' => 'SaKaLa', 'mm' => 'စကလ'],
        ['en' => 'WaLaMa', 'mm' => 'ဝလမ'],
        ['en' => 'HaKhaNa', 'mm' => 'ဟခန'],
        ['en' => 'LaWaNa', 'mm' => 'လဝန'],
        ['en' => 'HtaTaLa', 'mm' => 'ထတလ'],
        ['en' => 'HpaLaNa', 'mm' => 'ဖလန'],
        ['en' => 'RaKhaDa', 'mm' => 'ရခဒ'],
        ['en' => 'TaTaNa', 'mm' => 'တတန'],
        ['en' => 'RaPaTa', 'mm' => 'ရပသ'],
        ['en' => 'PaBaTa', 'mm' => 'ပဘတ'],
        ['en' => 'TaZaNa', 'mm' => 'တဇန'],
        ['en' => 'KaKhaNa', 'mm' => 'ကခန'],
        ['en' => 'MaTaNa', 'mm' => 'မတန'],
        ['en' => 'MaTaPa', 'mm' => 'မတပ'],
        ['en' => 'RaZaNa', 'mm' => 'ရဇန'],
        ['en' => 'KaPaLa', 'mm' => 'ကပလ'],
        ['en' => 'PaLaWa', 'mm' => 'ပလဝ'],
        ['en' => 'MaGaDa', 'mm' => 'မဂဒ'],
        ['en' => 'HsaMaNa', 'mm' => 'ဆမန'],
        ['en' => 'LaTaNa', 'mm' => 'လသန'],
        ['en' => 'SaKaNa', 'mm' => 'စကန'],
        ['en' => 'MaMaTa', 'mm' => 'မမတ'],
        ['en' => 'RaBaNa', 'mm' => 'ရဗန'],
        ['en' => 'WaLaNa', 'mm' => 'ဝလန'],
        ['en' => 'KhaUNa', 'mm' => 'ခဥန'],
        ['en' => 'UKaMa', 'mm' => 'ဥကမ'],
        ['en' => 'KaBaLa', 'mm' => 'ကဘလ'],
        ['en' => 'KaLaNa', 'mm' => 'ကလန'],
        ['en' => 'RaUNa', 'mm' => 'ရဥန'],
        ['en' => 'DaPaYa', 'mm' => 'ဒပယ'],
        ['en' => 'DaGaTa', 'mm' => 'ဒဂတ'],
        ['en' => 'TaHsaNa', 'mm' => 'တဆန'],
        ['en' => 'MaRaNa', 'mm' => 'မရန'],
        ['en' => 'KhaUTa', 'mm' => 'ခဥတ'],
        ['en' => 'ARaTa', 'mm' => 'အရတ'],
        ['en' => 'BaTaLa', 'mm' => 'ဘတလ'],
        ['en' => 'UKaTa', 'mm' => 'ဥကတ'],
        ['en' => 'YaMaPa', 'mm' => 'ယမပ'],
        ['en' => 'PaLaNa', 'mm' => 'ပလန'],
        ['en' => 'KaNaNa', 'mm' => 'ကနန'],
        ['en' => 'HsaLaKa', 'mm' => 'ဆလက'],
        ['en' => 'KaThaNa', 'mm' => 'ကသန'],
        ['en' => 'HtaKhaNa', 'mm' => 'ထခန'],
        ['en' => 'ATaNa', 'mm' => 'အတန'],
        ['en' => 'KaLaTa', 'mm' => 'ကလတ'],
        ['en' => 'PaLaBa', 'mm' => 'ပလဘ'],
        ['en' => 'WaThaNa', 'mm' => 'ဝသန'],
        ['en' => 'KaLaHta', 'mm' => 'ကလထ'],
        ['en' => 'KaLaWa', 'mm' => 'ကလဝ'],
        ['en' => 'MaKaNa', 'mm' => 'မကန'],
        ['en' => 'TaMaNa', 'mm' => 'တမန'],
        ['en' => 'KhaPaNa', 'mm' => 'ခပန'],
        ['en' => 'MaThaNa', 'mm' => 'မသန'],
        ['en' => 'KhaTaNa', 'mm' => 'ခတန'],
        ['en' => 'HaMaLa', 'mm' => 'ဟမလ'],
        ['en' => 'LaRaNa', 'mm' => 'လရန'],
        ['en' => 'LaHaNa', 'mm' => 'လဟန'],
        ['en' => 'LaTaYa', 'mm' => 'လသယ'],
        ['en' => 'NaYaNa', 'mm' => 'နယန'],
        ['en' => 'PaHsaNa', 'mm' => 'ပဆန'],
        ['en' => 'DaHaNa', 'mm' => 'ဒဟန'],
        ['en' => 'MaPaLa', 'mm' => 'မပလ'],
        ['en' => 'HtaPaKha', 'mm' => 'ထပခ'],
        ['en' => 'HsaMaRa', 'mm' => 'ဆမရ'],
        ['en' => 'NgaZaNa', 'mm' => 'ငဇန'],
        ['en' => 'AKhaNa', 'mm' => 'အခန'],
        ['en' => 'HtaWaNa', 'mm' => 'ထဝန'],
        ['en' => 'LaLaNa', 'mm' => 'လလန'],
        ['en' => 'ThaRaKha', 'mm' => 'သရခ'],
        ['en' => 'RaPhaNa', 'mm' => 'ရဖန'],
        ['en' => 'KaLaA', 'mm' => 'ကလအ'],
        ['en' => 'MaARa', 'mm' => 'မအရ'],
        ['en' => 'MaANa', 'mm' => 'မအန'],
        ['en' => 'KaSaNa', 'mm' => 'ကစန'],
        ['en' => 'TaThaRa', 'mm' => 'တသရ'],
        ['en' => 'PaLaTa', 'mm' => 'ပလတ'],
        ['en' => 'BaPaNa', 'mm' => 'ဘပန'],
        ['en' => 'KhaMaKa', 'mm' => 'ခမက'],
        ['en' => 'PaKaMa', 'mm' => 'ပကမ'],
        ['en' => 'KaRaRa', 'mm' => 'ကရရ'],
        ['en' => 'TaNgaNa', 'mm' => 'တငန'],
        ['en' => 'RaTaRa', 'mm' => 'ရတရ'],
        ['en' => 'HtaTaPa', 'mm' => 'ထတပ'],
        ['en' => 'HpaMaNa', 'mm' => 'ဖမန'],
        ['en' => 'KaKaNa', 'mm' => 'ကကန'],
        ['en' => 'PaKhaNa', 'mm' => 'ပခန'],
        ['en' => 'KaTaKha', 'mm' => 'ကတခ'],
        ['en' => 'NyaLaPa', 'mm' => 'ညလပ'],
        ['en' => 'DaUNa', 'mm' => 'ဒဥန'],
        ['en' => 'ThaNaPa', 'mm' => 'သနပ'],
        ['en' => 'KaWaNa', 'mm' => 'ကဝန'],
        ['en' => 'ThaWaTa', 'mm' => 'သဝတ'],
        ['en' => 'LaPaTa', 'mm' => 'လပတ'],
        ['en' => 'AHpaNa', 'mm' => 'အဖန'],
        ['en' => 'KaPaKa', 'mm' => 'ကပက'],
        ['en' => 'ZaKaNa', 'mm' => 'ဇကန'],
        ['en' => 'NaTaLa', 'mm' => 'နတလ'],
        ['en' => 'PaMaNa', 'mm' => 'ပမန'],
        ['en' => 'ThaKaNa', 'mm' => 'သကန'],
        ['en' => 'PaTaTa', 'mm' => 'ပတတ'],
        ['en' => 'PaTaNa', 'mm' => 'ပတန'],
        ['en' => 'PaKhaTa', 'mm' => 'ပခတ'],
        ['en' => 'RaNaKha', 'mm' => 'ရနခ'],
        ['en' => 'KhaMaNa', 'mm' => 'ခမန'],
        ['en' => 'TaTaKa', 'mm' => 'တတက'],
        ['en' => 'MaBaNa', 'mm' => 'မဘန'],
        ['en' => 'PaHpaNa', 'mm' => 'ပဖန'],
        ['en' => 'SaLaNa', 'mm' => 'စလန'],
        ['en' => 'SaTaRa', 'mm' => 'စတရ'],
        ['en' => 'NgaHpaNa', 'mm' => 'ငဖန'],
        ['en' => 'ThaRaNa', 'mm' => 'သရန'],
        ['en' => 'MaHtaNa', 'mm' => 'မထန'],
        ['en' => 'ALaNa', 'mm' => 'အလန'],
        ['en' => 'HsaPaWa', 'mm' => 'ဆပဝ'],
        ['en' => 'PaKhaKa', 'mm' => 'ပခက'],
        ['en' => 'RaSaKa', 'mm' => 'ရစက'],
        ['en' => 'HsaHpaNa', 'mm' => 'ဆဖန'],
        ['en' => 'GaGaNa', 'mm' => 'ဂဂန'],
        ['en' => 'HtaLaNa', 'mm' => 'ထလန'],
        ['en' => 'KaHtaNa', 'mm' => 'ကထန'],
        ['en' => 'MaNaMa', 'mm' => 'မနမ'],
        ['en' => 'AMaZa', 'mm' => 'အမဇ'],
        ['en' => 'MaRaMa', 'mm' => 'မရမ'],
        ['en' => 'KhaAZa', 'mm' => 'ခအဇ'],
        ['en' => 'MaNaTa', 'mm' => 'မနတ'],
        ['en' => 'KhaMaSa', 'mm' => 'ခမစ'],
        ['en' => 'MaRaTa', 'mm' => 'မရတ'],
        ['en' => 'MaHaMa', 'mm' => 'မဟမ'],
        ['en' => 'PaKaKha', 'mm' => 'ပကခ'],
        ['en' => 'AMaRa', 'mm' => 'အမရ'],
        ['en' => 'PaThaKa', 'mm' => 'ပသက'],
        ['en' => 'PaULa', 'mm' => 'ပဥလ'],
        ['en' => 'MaTaRa', 'mm' => 'မတရ'],
        ['en' => 'ThaPaKa', 'mm' => 'သပက'],
        ['en' => 'TaKaTa', 'mm' => 'တကတ'],
        ['en' => 'KaHsaNa', 'mm' => 'ကဆန'],
        ['en' => 'SaKaTa', 'mm' => 'စကတ'],
        ['en' => 'TaTaU', 'mm' => 'တတဥ'],
        ['en' => 'MaKhaNa', 'mm' => 'မခန'],
        ['en' => 'TaThaNa', 'mm' => 'တသန'],
        ['en' => 'NaHtaKa', 'mm' => 'နထက'],
        ['en' => 'NyaUNa', 'mm' => 'ညဥန'],
        ['en' => 'NgaThaRa', 'mm' => 'ငသရ'],
        ['en' => 'MaHtaLa', 'mm' => 'မထလ'],
        ['en' => 'ThaSaNa', 'mm' => 'သစန'],
        ['en' => 'WaTaNa', 'mm' => 'ဝတန'],
        ['en' => 'RaMaTha', 'mm' => 'ရမသ'],
        ['en' => 'PaBaNa', 'mm' => 'ပဘန'],
        ['en' => 'MaLaMa', 'mm' => 'မလမ'],
        ['en' => 'KaMaRa', 'mm' => 'ကမရ'],
        ['en' => 'KhaHsaNa', 'mm' => 'ခဆန'],
        ['en' => 'ThaHpaRa', 'mm' => 'သပရ'],
        ['en' => 'MaDaNa', 'mm' => 'မဒန'],
        ['en' => 'RaMaNa', 'mm' => 'ရမန'],
        ['en' => 'LaMaNa', 'mm' => 'လမန'],
        ['en' => 'KhaZaNa', 'mm' => 'ခဇန'],
        ['en' => 'ThaHtaNa', 'mm' => 'သထန'],
        ['en' => 'BaLaNa', 'mm' => 'ဘလန'],
        ['en' => 'SaTaNa', 'mm' => 'စတန'],
        ['en' => 'RaThaTa', 'mm' => 'ရသတ'],
        ['en' => 'PaNaKa', 'mm' => 'ပဏက'],
        ['en' => 'MaUNa', 'mm' => 'မဥန'],
        ['en' => 'MaPaNa', 'mm' => 'မပန'],
        ['en' => 'KaTaNa', 'mm' => 'ကတန'],
        ['en' => 'MaPaTa', 'mm' => 'မပတ'],
        ['en' => 'BaThaTa', 'mm' => 'ဘသတ'],
        ['en' => 'TaPaWa', 'mm' => 'တပဝ'],
        ['en' => 'KaHpaNa', 'mm' => 'ကဖန'],
        ['en' => 'AMaNa', 'mm' => 'အမန'],
        ['en' => 'TaKaNa', 'mm' => 'တကန'],
        ['en' => 'MaATa', 'mm' => 'မအတ'],
        ['en' => 'GaMaNa', 'mm' => 'ဂမန'],
        ['en' => 'KaTaLa', 'mm' => 'ကတလ'],
        ['en' => 'NyaRaNa', 'mm' => 'ညရန'],
        ['en' => 'HsaHsaNa', 'mm' => 'ဆဆန'],
        ['en' => 'PaTaYa', 'mm' => 'ပတယ'],
        ['en' => 'RaNgaNa', 'mm' => 'ရငန'],
        ['en' => 'RaSaNa', 'mm' => 'ရစန'],
        ['en' => 'HpaKhaNa', 'mm' => 'ဖခန'],
        ['en' => 'NaTaRa', 'mm' => 'နတရ'],
        ['en' => 'LaKhaNa', 'mm' => 'လခန'],
        ['en' => 'NaSaNa', 'mm' => 'နစန'],
        ['en' => 'KaHaNa', 'mm' => 'ကဟန'],
        ['en' => 'KhaLaNa', 'mm' => 'ခလန'],
        ['en' => 'KaLaDa', 'mm' => 'ကလဒ'],
        ['en' => 'LaKhaTa', 'mm' => 'လခတ'],
        ['en' => 'MaNaNa', 'mm' => 'မနန'],
        ['en' => 'HaMaNa', 'mm' => 'ဟမန'],
        ['en' => 'KaTaTa', 'mm' => 'ကတတ'],
        ['en' => 'ThaNaNa', 'mm' => 'သနန'],
        ['en' => 'TaYaNa', 'mm' => 'တယန'],
        ['en' => 'PaYaNa', 'mm' => 'ပယန'],
        ['en' => 'NaHpaNa', 'mm' => 'နဖန'],
        ['en' => 'MaHpaTa', 'mm' => 'မဖတ'],
        ['en' => 'MaKaHta', 'mm' => 'မကထ'],
        ['en' => 'MaHsaTa', 'mm' => 'မဆတ'],
        ['en' => 'NaKhaNa', 'mm' => 'နခန'],
        ['en' => 'TaMaNja', 'mm' => 'တမည'],
        ['en' => 'MaHaRa', 'mm' => 'မဟရ'],
        ['en' => 'PaHsaTa', 'mm' => 'ပဆတ'],
        ['en' => 'ThaPaNa', 'mm' => 'သပန'],
        ['en' => 'NaKhaTa', 'mm' => 'နခတ'],
        ['en' => 'NaMaTa', 'mm' => 'နမတ'],
        ['en' => 'NaHsaNa', 'mm' => 'နဆန'],
        ['en' => 'MaTaTa', 'mm' => 'မတတ'],
        ['en' => 'MaNgaNa', 'mm' => 'မငန'],
        ['en' => 'MaLaTa', 'mm' => 'မလတ'],
        ['en' => 'HaPaTa', 'mm' => 'ဟပတ'],
        ['en' => 'MaMaHta', 'mm' => 'မမထ'],
        ['en' => 'NaTaNa', 'mm' => 'နတန'],
        ['en' => 'PaLaHta', 'mm' => 'ပလထ'],
        ['en' => 'KhaRaHa', 'mm' => 'ခရဟ'],
        ['en' => 'MaHtaTa', 'mm' => 'မထတ'],
        ['en' => 'MaYaNa', 'mm' => 'မယန'],
        ['en' => 'MaPaHta', 'mm' => 'မပထ'],
        ['en' => 'MaHsaNa', 'mm' => 'မဆန'],
        ['en' => 'MaKhaTa', 'mm' => 'မခတ'],
        ['en' => 'PaPaKa', 'mm' => 'ပပက'],
        ['en' => 'MaHpaNa', 'mm' => 'မဖန'],
        ['en' => 'MaYaTa', 'mm' => 'မယတ'],
        ['en' => 'MaYaHta', 'mm' => 'မယထ'],
        ['en' => 'TaKhaLa', 'mm' => 'တခလ'],
        ['en' => 'TaLaNa', 'mm' => 'တလန'],
        ['en' => 'PaThaNa', 'mm' => 'ပသန'],
        ['en' => 'RaThaYa', 'mm' => 'ရသယ'],
        ['en' => 'NgaHsaNa', 'mm' => 'ငဆန'],
        ['en' => 'PaThaRa', 'mm' => 'ပသရ'],
        ['en' => 'KaKaHta', 'mm' => 'ကကထ'],
        ['en' => 'NgaPaTa', 'mm' => 'ငပတ'],
        ['en' => 'HaKaKa', 'mm' => 'ဟကက'],
        ['en' => 'NgaRaKa', 'mm' => 'ငရက'],
        ['en' => 'NgaThaKha', 'mm' => 'ငသခ'],
        ['en' => 'KaPaNa', 'mm' => 'ကပန'],
        ['en' => 'HaThaTa', 'mm' => 'ဟသတ'],
        ['en' => 'ZaLaNa', 'mm' => 'ဇလန'],
        ['en' => 'AGaPa', 'mm' => 'အဂပ'],
        ['en' => 'MaAPa', 'mm' => 'မအပ'],
        ['en' => 'NyaTaNa', 'mm' => 'ညတန'],
        ['en' => 'DaNaHpa', 'mm' => 'ဓနဖ'],
        ['en' => 'AMaTa', 'mm' => 'အမတ'],
        ['en' => 'BaKaLa', 'mm' => 'ဘကလ'],
        ['en' => 'DaDaRa', 'mm' => 'ဒဒရ'],
        ['en' => 'PaSaLa', 'mm' => 'ပစလ'],
        ['en' => 'MaMaKa', 'mm' => 'မမက'],
        ['en' => 'WaKhaMa', 'mm' => 'ဝခမ'],
        ['en' => 'UTaTha', 'mm' => 'ဥတသ'],
        ['en' => 'ZaYaTha', 'mm' => 'ဇယသ'],
        ['en' => 'PaBaTha', 'mm' => 'ပဗသ'],
        ['en' => 'DaKhaTha', 'mm' => 'ဒခသ'],
        ['en' => 'DaGaNa', 'mm' => 'ဒဂန'],
        ['en' => 'DaGaHsa', 'mm' => 'ဒဂဆ'],
        ['en' => 'DaLaNa', 'mm' => 'ဒလန'],
        ['en' => 'DaPaNa', 'mm' => 'ဒပန'],
        ['en' => 'DaGaRa', 'mm' => 'ဒဂရ'],
        ['en' => 'ZaBaTha', 'mm' => 'ဇဘသ'],
    ],

    'townships' => [

        '1' => [
            'BaMaNa' => 'Banmaw Township',
            'KhaPhaNa' => 'Chibwe Township',
            'TaNaNa' => 'Tanai Township',
            'HpaKaNa' => 'Hpakant Township',
            'KhaLaHpa' => 'Kawnglanghpu Township',
            'HpaKaNa' => 'Hpakant Township',
            'MaKhaBa' => 'Machanbaw Township',
            'MaSaNa' => 'Mansi Township',
            'MaKaTa' => 'Mogaung Township',
            'MaNjaNa' => 'Mohnyin Township',
            'MaMaNa' => 'Momauk Township',
            'MaKaNa' => 'Myitkyina Township',
            'AGaYa' => 'Injangyang Township',
            'NaMaNa' => 'Nogmung Township',
            'PaTaA' => 'Putao Township',
            'RaKaNa' => 'Shwegu Township',
            'HsaBaNa' => 'Sumprabum Township',
            'HsaLaNa' => 'Hsawlaw Township',
            'WaMaNa' => 'Waimaw Township',
        ],

        '၁' => [
            'ဗမန' => 'ဗန်းမော်မြို့နယ်',
            'ခဖန' => 'ချီဖွေမြို့နယ်',
            'တနန' => 'တနိုင်းမြို့နယ်',
            'ဖကန' => 'ဖားကန့်မြို့နယ်',
            'ခလဖ' => 'ခေါင်လန်ဖူးမြို့နယ်',
            'ဖကန' => 'ဖားကန့်မြို့နယ်',
            'မခဘ' => 'မချမ်းဘောမြို့နယ်',
            'မစန' => 'မံစီမြို့နယ်',
            'မကတ' => 'မိုးကောင်းမြို့နယ်',
            'မညန' => 'မိုးညှင်းမြို့နယ်',
            'မမန' => 'မိုးမောက်မြို့နယ်',
            'မကန' => 'မြစ်ကြီးနားမြို့နယ်',
            'အဂယ' => 'အင်ဂျန်းယန်မြို့နယ်',
            'နမန' => 'နောင်မွန်းမြို့နယ်',
            'ပတအ' => 'ပူတာအိုမြို့နယ်',
            'ရကန' => 'ရွှေကူမြို့နယ်',
            'ဆဘန' => 'ဆွမ်ပရာဘွမ်မြို့နယ်',
            'ဆလန' => 'ဆော့လော်မြို့နယ်',
            'ဝမန' => 'ဝိုင်းမော်မြို့နယ်',
        ],

        '2' => [
            'BaLaKha' => 'Bawlakhe Township ',
            'DaMaSa' => 'Demoso Township',
            'HpaHsaNa' => 'Hpasawng Township',
            'HpaRaHsa' => 'Hpruso Township',
            'LaKaNa' => 'LoiKaw Township',
            'MaHsaNa' => 'Mese Township',
            'RaTaNa' => 'Shadaw Township',
        ],

        '၂' => [
            'ဘလခ' => 'ဘော်လခဲမြို့နယ်',
            'ဒမဆ' => 'ဒီမောဆိုးမြို့နယ်',
            'ဖဆန' => 'ဖားဆောင်းမြို့နယ်',
            'ဖရဆ' => 'ဖရူဆိုမြို့နယ်',
            'လကန' => 'လ္လိုင်ကော်မြို့နယ်',
            'မဆန' => 'မယ့်စဲ့မြို့နယ်',
            'ရတန' => 'ရှားတောမြို့နယ်',
        ],

        '3' => [
            'LaBaNa' => 'Hlaingbwe Township',
            'BaANa' => 'Hpa-an Township',
            'HpaPaNa' => 'Hpapun Township',
            'KaKaRa' => 'Kawkareik Township',
            'KaHsaKa' => 'Kyain Seikgyi Township',
            'MaWaTa' => 'Myawaddy Township',
            'ThaTaKa' => 'Thandaunggyi Township',
        ],

        '၃' => [
            'လဘန' => 'လှိုင်းဘွဲ့မြို့နယ်',
            'ဘအန' => 'ဘားအံမြို့နယ်',
            'ဖပန' => 'ဖားပွန်မြို့နယ်',
            'ကကရ' => 'ကော့ကရိတ်မြို့နယ်',
            'ကဆက' => 'ကြာအင်းဆိပ်ကြီးမြို့နယ်',
            'မဝတ' => 'မြဝတီမြို့နယ်',
            'သတက' => 'သံတောင်ကြီးမြို့နယ်',
        ],

        '4' => [
            'HpaLaNa' => 'Falam Township',
            'HaKhaNa' => 'Hakha Township',
            'KaPaLa' => 'Kanpetlet Township',
            'MaTaPa' => 'Matupi Township',
            'MaTaNa' => 'Mindat Township',
            'PaLaWa' => 'Paletwa Township',
            'TaTaNa' => 'Tedim Township',
            'HtaTaLa' => 'Thantlang Township',
            'TaZaNa' => 'Tonzang Township',
        ],

        '၄' => [
            'ဖလန' => 'ဖလင်းမြို့နယ်',
            'ဟခန' => 'ဟားခါးမြို့နယ်',
            'ကပလ' => 'ကန်ပက်လက်မြို့နယ်',
            'မတပ' => 'မတူပီမြို့နယ်',
            'မတန' => 'မင်းတပ်မြို့နယ်',
            'ပလဝ' => 'ပလက်ဝမြို့နယ်',
            'တတန' => 'တီးတိန်မြို့နယ်',
            'ထတလ' => 'ထန်တလန်မြို့နယ်',
            'တဇန' => 'တွန်းဇံမြို့နယ်',
        ],

        '5' => [
            "ARaTa" => 'Ayadaw Township',
            "BaMaNa" => 'Banmauk Township',
            "BaTaLa" => 'Budalin Township',
            "KhaUNa" => 'Chaung-U Township',
            "KhaTaNa" => 'Hkamti Township',
            'HaMaLa' => 'Homalin Township',
            "ATaNa" => 'Indaw Township',
            "KaLaNa" => 'Kale Township',
            "KaLaWa" => 'Kalewa Township',
            "KaBaLa" => 'Kanbalu Township',
            "KaNaNa" => "Kani Township",
            "KaThaNa" => "Katha Township",
            "KaLaTa" => "Kawlin Township",
            "KaLaNa" => "Kyunhla Township",
            "LaHaNa" => "Lahe Township",
            "LaRaNa" => "Leshi Township",
            "MaLaNa" => "Mawlaik Township",
            "MaKaNa" => "Mingin Township",
            "MaRaNa" => "Monywa Township",
            "MaMaNa" => "Myaung Township",
            "NaYaNa" => "Nanyun Township",
            "PaLaNa" => "Pale Township",
            "HpaPaNa" => "Paungbyin Township",
            "PaLaBa" => "Pinlebu Township",
            "SaKaNa" => "Sagaing Township",
            "HsaLaKa" => "Salingyi Township",
            "RaBaNa" => "Shwebo Township",
            "DaPaYa" => "Tabayin Township",
            "TaMaNa" => "Tamu Township",
            "HtaKhaNa" => "Htigyaing Township",
            "WaLaNa" => "Wetlet Township",
            "WaThaNa" => "Wuntho Township",
            "RaUNa" => "Ye-U Township",
            "YaMaPa" => "Yinmabin Township",
            "ThaLaHta" => "TaLinn Township",
        ],

        '၅' => [
            "အရတ" => 'အရာတော်မြို့နယ်',
            "ဗမန" => 'ဗန်းမောက်မြို့နယ်',
            "ဘတလ" => 'ဘုတလင်မြို့နယ်',
            "ခဥန" => 'ချောင်းဦးမြို့နယ်',
            "ခတန" => 'ခန္တီးမြို့နယ်',
            "ဟမလ" => 'ဟုမ္မလင်းမြို့နယ်',
            "အတန" => 'အင်းတော်မြို့နယ်',
            "ကလန" => 'ကလေးမြို့နယ်',
            "ကလဝ" => 'ကလေးဝမြို့နယ်',
            "ကဘလ" => 'ကန့်ဘလူမြို့နယ်',
            "ကနန" => 'ကနီမြို့နယ်',
            "ကသန" => 'ကသာမြို့နယ်',
            "ကလတ" => 'ကောလင်းမြို့နယ်',
            "ကလန" => 'ကျွန်းလှမြို့နယ်',
            "လဟန" => 'လဟယ်မြို့နယ်',
            "လရန" => 'လေရှီးမြို့နယ်',
            "မလန" => 'မော်လိုက်မြို့နယ်',
            "မကန" => 'မင်းကင်းမြို့နယ်',
            "မရန" => 'မုံရွာမြို့နယ်',
            "မမန" => 'မြောင်မြို့နယ်',
            "နယန" => 'နန်းယွန်းမြို့နယ်',
            "ပလန" => 'ပုလဲမြို့နယ်',
            "ဖပန" => 'ဖောင်းပြင်မြို့နယ်',
            "ပလဘ" => 'ပင်လည်ဘူးမြို့နယ်',
            "စကန" => 'စစ်ကိုင်းမြို့နယ်',
            "ဆလက" => 'ဆားလင်းကြီးမြို့နယ်',
            "ရဘန" => 'ရွှေဘိုမြို့နယ်',
            "ဒပယ" => 'ဒီပဲယင်းမြို့နယ်',
            "တမန" => 'တမူးမြို့နယ်',
            "ထခန" => 'ထီးချိုင့်မြို့နယ်',
            "ဝလန" => 'ဝက်လက်မြို့နယ်',
            "ဝသန" => 'ဝန်းသိုမြို့နယ်',
            "ရဥန" => 'ရေဦးမြို့နယ်',
            "ယမပ" => 'ယင်းမာပင်မြို့နယ်',
            "သလထ" => 'သလင်းမြို့နယ်',
        ],

        '6' => [
            'BaPaNa' => 'Bokepyin Township',
            'HtaWaNa' => 'Dawei Township',
            'KaThaNa' => 'Kawthaung Township',
            'KaSaNa' => 'Kyunsu Township',
            'LaLaNa' => 'Launglon Township',
            'MaMaNa' => 'Myeik Township',
            'PaLaNa' => 'Palaw Township',
            'TaThaRa' => 'Tanintharyi Township',
            'ThaRaKha' => 'Thayetchaung Township',
        ],

        '၆' => [
            'ဘပန' => 'ဘုတ်ပြင်းမြို့နယ်',
            'ထဝန' => 'ထားဝယ်မြို့နယ်',
            'ကသန' => 'ကော့သောင်းမြို့နယ်',
            'ကစန' => 'ကျွန်းစုမြို့နယ်',
            'လလန' => 'လောင်းလုံမြို့နယ်',
            'မမန' => 'မြိတ်မြို့နယ်',
            'ပလန' => 'ပုလောမြို့နယ်',
            'တသရ' => 'တနင်္သာရီမြို့နယ်',
            'သရခ' => 'သရက်ချောင်းမြို့နယ်',
        ],

        '7' => [
            'PaKhaNa' => 'Bago Township',
            'DaUNa' => 'Daik-U Township',
            'KaPaKa' => 'Gyobingauk Township',
            'HtaTaPa' => 'Tantabin Township',
            'KaWaNa' => 'Kawa Township',
            'KaKaNa' => 'Kyaukkyi Township',
            'KaTaKha' => 'Kyauktaga Township',
            'LaPaTa' => 'Letpadan Township',
            'MaLaNa' => 'Minhla Township',
            'MaNyaNa' => 'Monyo Township',
            'NaTaLa' => 'Nattalin Township',
            'NyaLaPa' => 'Nyaunglebin Township',
            'AHpaNa' => 'Okpho Township',
            'ATaNa' => 'Oktwin Township',
            'PaTaNa' => 'Pandaung Township',
            'PaKhaTa' => 'Paukkaung Township',
            'PaTaTa' => 'Paungde Township',
            'HpaMaNa' => 'Pyu Township',
            'PaMaNa' => 'Pyay Township',
            'RaTaNa' => 'Shwedaung Township',
            'RaKaNa' => 'Shwegyin Township',
            'TaNgaNa' => 'Taungoo Township',
            'ThaNaPa' => 'Thanatpin Township',
            'ThaWaTa' => 'Tharrawaddy Township',
            'ThaKaNa' => 'Thegon Township',
            'WaMaNa' => 'Waw Township',
            'RaTaRa' => 'Yedashe Township',
            'ZaKaNa' => 'Zigon Township',
        ],

        '၇' => [
            'ပခန' => 'ပဲခူးမြို့နယ်',
            'ဒဥန' => 'ဒိုက်ဦးမြို့နယ်',
            'ကပက' => 'ကြို့ပင်ကောက်မြို့နယ်',
            'ထတပ' => 'ထန်းတပင်မြို့နယ်',
            'ကဝန' => 'ကဝမြို့နယ်',
            'ကကန' => 'ကျောက်ကြီးမြို့နယ်',
            'ကတခ' => 'ကျောက်တံခါးမြို့နယ်',
            'လပတ' => 'လက်ပံတန်းမြို့နယ်',
            'မလန' => 'မင်းလှမြို့နယ်',
            'မညန' => 'မိုးညိုမြို့နယ်',
            'နတလ' => 'နတ်တလင်းမြို့နယ်',
            'ညလပ' => 'ညောင်လေးပင်မြို့နယ်',
            'အဖန' => 'အုတ်ဖိုမြို့နယ်',
            'အတန' => 'အုတ်တွင်းမြို့နယ်',
            'ပတန' => 'ပန်းတောင်းမြို့နယ်',
            'ပခတ' => 'ပေါင်ခေါင်းမြို့နယ်',
            'ပတတ' => 'ပေါင်းတည်မြို့နယ်',
            'ဖမန' => 'ဖြူးမြို့နယ်',
            'ပမန' => 'ပြည်မြို့နယ်',
            'ရတန' => 'ရွှေတောင်မြို့နယ်',
            'ရကန' => 'ရွှေကျင်မြို့နယ်',
            'တငန' => 'တောင်ငူမြို့နယ်',
            'သနပ' => 'သနပ်ပင်မြို့နယ်',
            'သဝတ' => 'သာယာဝတီမြို့နယ်',
            'သကန' => 'သဲကုန်းမြို့နယ်',
            'ဝမန' => 'ဝေါမြို့နယ်',
            'ရတရ' => 'ရေတာရှည် မြို့နယ်ရ',
            'ဇကန' => 'ဇီးကုန်းမြို့နယ်',
        ],

        '8' => [
            'အလန' => 'အောင်လံမြို့နယ်',
            'ခမန' => 'ချောက်မြို့နယ်',
            'ဂဂန' => 'ဂန့်ဂေါမြို့နယ်',
            'ကမန' => 'ကံမမြို့နယ်',
            'မကန' => 'မကွေးမြို့နယ်',
            'မဘန' => 'မင်းဘူးမြို့နယ်',
            'မတန' => 'မင်းတုန်းမြို့နယ်',
            'မလန' => 'မင်းလှမြို့နယ်',
            'မမန' => 'မြိုင်မြို့နယ်',
            'မသန' => 'မြို့သစ်မြို့နယ်',
            'နမန' => 'နတ်မောက်မြို့နယ်',
            'ငဖန' => 'ငဖဲမြို့နယ်',
            'ပခက' => 'ပခုက္ကူမြို့နယ်',
            'ပမန' => 'ပေါက်မြို့နယ်',
            'ပဖန' => 'ပွင့်ဖြူမြို့နယ်',
            'စလန' => 'စလင်းမြို့နယ်',
            'ဆမန' => 'ဆောမြို့နယ်',
            'ဆဖန' => 'ဆိပ်ဖြူမြို့နယ်',
            'စတရ' => 'စေတုတ္တရာမြို့နယ်',
            'ဆပဝ' => 'ဆင်ပေါင်ဝဲမြို့နယ်',
            'တတက' => 'တောင်တွင်းကြီးမြို့နယ်',
            'သရန' => 'သရက်မြို့နယ်',
            'ထလန' => 'ထီးလင်းမြို့နယ်',
            'ရနခ' => 'ရေနံချောင်းမြို့နယ်',
            'ရစက' => 'ရေစကြိုမြို့နယ်',
        ],

        '၈' => [
            'ALaNa' => 'Aunglan Township',
            'KhaMaNa' => 'Chauk Township',
            'GaGaNa' => 'Gangaw Township',
            'KaMaNa' => 'Kamma Township',
            'MaKaNa' => 'Magway Township',
            'MaBaNa' => 'Minbu Township',
            'MaTaNa' => 'Mindon Township',
            'MaLaNa' => 'Minhla Township',
            'MaMaNa' => 'Myaing Township',
            'MaThaNa' => 'Myothit Township',
            'NaMaNa' => 'Natmauk Township',
            'NgaHpaNa' => 'Ngape Township',
            'PaKhaKa' => 'Pakokku Township',
            'PaMaNa' => 'Pauk Township',
            'PaHpaNa' => 'Pwintbyu Township',
            'SaLaNa' => 'Salin Township',
            'HsaMaNa' => 'Saw Township',
            'HsaHpaNa' => 'Seikphyu Township',
            'SaTaRa' => 'Sidoktaya Township',
            'HsaPaWa' => 'Sinbaungwe Township',
            'TaTaKa' => 'Taungdwingyi Township',
            'ThaRaNa' => 'Thayet Township',
            'HtaLaNa' => 'Htilin Township',
            'RaNaKha' => 'Yenangyaung Township',
            'RaSaKa' => 'Yesagyo Township',
        ],

        '9' => [
            'AMaRa' => 'Amarapura Township',
            'AMaZa' => 'Aungmyethazan Township',
            'KhaAZa' => 'Chanayethazan Township',
            'KhaMaTa' => 'Chanmyathazi Township',
            'KaPaTa' => 'Kyaukpadaung Township',
            'KaHsaNa' => 'Kyaukse Township',
            'MaTaRa' => 'Madaya Township',
            'MaHaMa' => 'Maha Aungmye Township',
            'MaLaNa' => 'Mahlaing Township',
            'MaHtaLa' => 'Meiktila Township',
            'MaKaNa' => 'Mogok Township',
            'MaKhaNa' => 'Myingyan Township',
            'MaThaNa' => 'Myittha Township',
            'NaHtaKa' => 'Natogyi Township',
            'NgaZaNa' => 'Nganzun Township',
            'NyaUNa' => 'Nyaung-U Township',
            'PaKaTa' => 'Patheingyi Township',
            'PaBaNa' => 'Pyawbwe Township',
            'PaKaKha' => 'Pyigyidagun Township',
            'PaULa' => 'Pyioolwin Township',
            'SaKaNa' => 'Sintgaing Township',
            'TaTaU' => 'Tada-U Township',
            'TaThaNa' => 'Taungtha Township',
            'ThaPaKa' => 'Thabeikkyin Township',
            'ThaSaNa' => 'Thazi Township',
            'WaTaNa' => 'Wundwin Township',
            'RaMaTha' => 'Yamethin Township',
            'DaKhaTha' => 'Dekkhinathiri Township',
            'LaWaNa' => 'Lewe Township',
            'UTaTha' => 'Ottarathiri Township',
            'PaBaTha' => 'Pobbathiri Township',
            'PaMaNa' => 'Pyinmana Township',
            'TaKaNa' => 'Tatkone Township',
            'ZaBaTha' => 'Zabuthiri Township',
            'ZaYaTha' => 'Zeyathiri Township',
            'MaRaMa' => 'Manshaemyauk',
            'MaNaMa' => 'Mannaukmyauk',
        ],

        '၉' => [
            'အမရ' => 'အမရပူရမြို့နယ်',
            'အမဇ' => 'အောင်မြေသာဇံမြို့နယ်',
            'ခအဇ' => 'ချမ်းအေးသာဇံမြို့နယ်',
            'ခမသ' => 'ချမ်းမြသာစည်မြို့နယ်',
            'ကပတ' => 'ကျောက်ပန်းတောင်းမြို့နယ်',
            'ကဆန' => 'ကျောက်ဆည်မြို့နယ်',
            'မတရ' => 'မတ္တရာမြို့နယ်',
            'မဟမ' => 'မဟာအောင်မြေမြို့နယ်',
            'မလန' => 'မလှိုင်မြို့နယ်',
            'မထလ' => 'မိတ္တီလာမြို့နယ်',
            'မကန' => 'မိုးကုတ်မြို့နယ်',
            'မခန' => 'မြင်းခြံမြို့နယ်',
            'မသန' => 'မြစ်သားမြို့နယ်',
            'နထက' => 'နွားထိုးကြီးမြို့နယ်',
            'ငဇန' => 'ငါန်းဇွန်မြို့နယ်',
            'ညဥန' => 'ညောင်ဦးမြို့နယ်',
            'ပသက' => 'ပုသိမ်ကြီးမြို့နယ်',
            'ပဘန' => 'ပျော်ဘွယ်မြို့နယ်',
            'ပကခ' => 'ပြည်ကြီးတံခွန်မြို့နယ်',
            'ပဥလ' => 'ပြင်ဦးလွင်မြို့နယ်',
            'စကန' => 'စဥ့်ကိုင်မြို့နယ်',
            'တတဥ' => 'တံတားဦးမြို့နယ်',
            'တသန' => 'တောင်သာမြို့နယ်',
            'သပက' => 'သပိတ်ကျဥ်းမြို့နယ်',
            'သစန' => 'သာစည်မြို့နယ်',
            'ဝတန' => 'ဝမ်းတွင်းမြို့နယ်',
            'ရမသ' => 'ရမည်းသင်းမြို့နယ်',
            'ဒခသ' => 'ဒက္ခိဏသီရိမြို့နယ်',
            'လဝန' => 'လယ်ဝေးမြို့နယ်',
            'ဥတသ' => 'ဥတ္တရသီရိမြို့နယ်',
            'ပဗသ' => 'ပုဗ္ဗသီရိမြို့နယ်',
            'ပမန' => 'ပျဥ်းမနားမြို့နယ်',
            'တကန' => 'တပ်ကုန်းမြို့နယ်',
            'ဇဗသ' => 'ဇမ္ဗူသီရိမြို့နယ်',
            'ဇယသ' => 'ဇေယျာသီရိမြို့နယ်',
            'မရမ' => 'မန်းရှေ့မြောက်',
            'မနမ' => 'မန်းနောက်မြောက်',
        ],

        '10' => [
            'BaLaNa' => 'Bilin Township',
            'KhaHsaNa' => 'Chaungzon Township',
            'KaMaRa' => 'Kyaikmaraw Township',
            'MaLaMa' => 'Mawlamyine Township',
            'MaDaNa' => 'Mudon Township',
            'PaMaNa' => 'Paung Township',
            'ThaHpaRa' => 'Thanbyuzayat Township',
            'ThaHtaNa' => 'Thaton Township',
            'RaMaNa' => 'Ye Township',
            'KaHtaNa' => 'Kyaikto Township',
        ],

        '၁၀' => [
            'ဘလန' => 'ဘီးလင်းမြို့နယ်',
            'ခဆန' => 'ချောင်းဆုံမြို့နယ်',
            'ကမရ' => 'ကျိုက်မရောမြို့နယ်',
            'မလမ' => 'မော်လမြိုင်မြို့နယ်',
            'မဒန' => 'မုဒုံမြို့နယ်',
            'ပမန' => 'ပေါင်မြို့နယ်',
            'သဖရ' => 'သံဖြူဇရပ်မြို့နယ်',
            'သထန' => 'သထုံမြို့နယ်',
            'ရမန' => 'ရေးမြို့နယ်',
            'ကထန' => 'ကျိုက်ထိုမြို့နယ်',
        ],

        '11' => [
            'AMaNa' => 'Ann Township',
            'BaThaTa' => 'Buthidaung Township',
            'GaMaNa' => 'Gwa Township',
            'KaHpaNa' => 'Kyaukphyu Township',
            'KaTaNa' => 'Kyauktaw Township',
            'MaTaNa' => 'Maungtaw Township',
            'MaUNa' => 'Mrauk-U Township',
            'MaPaNa' => 'Myebon Township',
            'PaTaNa' => 'Pauktaw Township',
            'PaNaKa' => 'Ponnagyun Township',
            'RaBaNa' => 'Ramree Township',
            'RaThaTa' => 'Rathedaung Township',
            'SaTaNa' => 'Sittwe Township',
            'ThaTaNa' => 'Thandwe Township',
            'TaKaNa' => 'Taungup Township',
        ],

        '၁၁' => [
            'အမန' => 'အမ်းမြို့နယ်',
            'ဘသတ' => 'ဘူးသီးတောင်မြို့နယ်',
            'ဂမန' => 'ဂွမြို့နယ်',
            'ကဖန' => 'ကျောက်ဖြူမြို့နယ်',
            'ကတန' => 'ကျောက်တော်မြို့နယ်',
            'မတန' => 'မောင်တောမြို့နယ်',
            'မဥန' => 'မြောက်ဦးမြို့နယ်',
            'မပန' => 'မြေပုံမြို့နယ်',
            'ပတန' => 'ပေါက်တောမြို့နယ်',
            'ပဏက' => 'ပုဏ္ဏားကျွန်းမြို့နယ်',
            'ရဗန' => 'ရမ်းဗြဲမြို့နယ်',
            'ရသတ' => 'ရသေ့တောင်မြို့နယ်',
            'စတန' => 'စစ်တွေမြို့နယ်',
            'သတန' => 'သံတွဲမြို့နယ်',
            'တကန' => 'တောင်ကုတ်မြို့နယ်',
        ],

        '12' => [
            'ALaNa' => 'Ahlon Township',
            'BaHaNa' => 'Bahan Township',
            'KaKaKa' => 'Cocokyun Township',
            'DaGaNa' => 'Dagon Township',
            'DaGaHsa' => 'Dagon Seikkan Township',
            'DaLaNa' => 'Dala Township',
            'DaPaNa' => 'Dawbon Township',
            'DaGaRa' => 'East Dagon Township',
            'LaMaNa' => 'Hlaing Township',
            'LaTaYa' => 'Hlaingthaya Township',
            'LaKaNa' => 'Hlegu Township',
            'BaTaHta' => 'Botataung Township',
            'MaBaNa' => 'Hmawbi Township',
            'HtaTaPa' => 'Htantabin Township',
            'ASaNa' => 'Insein Township',
            'KaMaRa' => 'Kamayut Township',
            'KhaNaTa' => 'Kanaungto Township',
            'KaMaNa' => 'Kawhmu Township',
            'KhaRaNa' => 'Kayan Township',
            'KaKhaKa' => 'Kungyangon Township',
            'KaTaTa' => 'Kyauktada Township',
            'KaTaNa' => 'Kyauktan Township',
            'KaMaTa' => 'Kyimyindaing Township',
            'LaMaTa' => 'Lanmadaw Township',
            'LaTaNa' => 'Latha Township',
            'MaRaKa' => 'Mayangon Township',
            'MaGaDa' => 'Mingaladon Township',
            'MaGaTa' => 'Mingala Taungnyunt Township',
            'DaGaMa' => 'North Dagon Myothit Township',
            'UKaMa' => 'North Okkalapa Township',
            'PaBaTa' => 'Pabedan Township',
            'PaZaTa' => 'Pazundaung Township',
            'SaKhaNa' => 'Sanchaung Township',
            'HsaKaNa' => 'Seikkan Township',
            'RaPaTa' => 'Shwepyitha Township',
            'DaGaTa' => 'South Dagon Myothit Township',
            'UKaTa' => 'South Okkalapa Township',
            'TaKaNa' => 'Taikkyi Township',
            'TaMaNa' => 'Tamwe Township',
            'ThaKaTa' => 'Thaketa Township',
            'ThaLaNa' => 'Thanlyin Township',
            'ThaGhaKa' => 'Thingangyun Township',
            'ThaKhaNa' => 'Thongwa Township',
            'TaTaNa' => 'Twante Township',
            'RaKaNa' => 'Yankin Township',
        ],

        '၁၂' => [
            'အလန' => 'အလုံမြို့နယ်',
            'ဗဟန' => 'ဗဟန်းမြို့နယ်',
            'ကကက' => 'ကိုကိုးကျွန်းမြို့နယ်',
            'ဒဂန' => 'ဒဂုံမြို့နယ်',
            'ဒဂဆ' => 'ဒဂုံဆိပ်ကမ်းမြို့နယ်',
            'ဒလန' => 'ဒလမြို့နယ်',
            'ဒပန' => 'ဒေါပုံမြို့နယ်',
            'ဒဂရ' => 'ဒဂုံမြို့သစ်အရှေ့ပိုင်းမြို့နယ်',
            'လမန' => 'လှိုင်မြို့နယ်',
            'လသယ' => 'လှိုင်သာယာမြို့နယ်',
            'လကန' => 'လှည်းကူးမြို့နယ်',
            'ဗတထ' => 'ဗိုလ်တထောင်မြို့နယ်',
            'မဘန' => 'မှော်ဘီမြို့နယ်',
            'ထတပ' => 'ထန်းတပင်မြို့နယ်',
            'အစန' => 'အင်းစိန်မြို့နယ်',
            'ကမရ' => 'ကမာရွတ်မြို့နယ်',
            'ခနတ' => 'ခနောင်တိုမြို့နယ်',
            'ကမန' => 'ကော့မှူးမြို့နယ်',
            'ခရန' => 'ခရမ်းမြို့နယ်',
            'ကခက' => 'ကွမ်းခြံကုန်းမြို့နယ်',
            'ကတတ' => 'ကျောက်တံတားမြို့နယ်',
            'ကတန' => 'ကျောက်တန်းမြို့နယ်',
            'ကမတ' => 'ကြည့်မြင့်တိုင်မြို့နယ်',
            'လမတ' => 'လမ်းမတော်မြို့နယ်',
            'လသန' => 'လသာမြို့နယ်',
            'မရက' => 'မရမ်းကုန်းမြို့နယ်',
            'မဂဒ' => 'မင်္ဂလာဒုံမြို့နယ်',
            'မဂတ' => 'မင်္ဂလာတောင်ညွှန့်မြို့နယ်',
            'ဒဂမ' => 'ဒဂုံမြို့သစ်မြောက်ပိုင်းမြို့နယ်',
            'ဥကမ' => 'မြောက်ဉက္ကလာပမြို့နယ်',
            'ပဘတ' => 'ပန်းဘဲတန်းမြို့နယ်',
            'ပဇတ' => 'ပုစွန်တောင်မြို့နယ်',
            'စခန' => 'စမ်းချောင်းမြို့နယ်',
            'ဆကန' => 'ဆိပ်ကမ်းမြို့နယ်',
            'ရပသ' => 'ရွှေပြည်သာမြို့နယ်',
            'ဒဂတ' => 'ဒဂုံမြို့သစ်တောင်ပိုင်းမြို့နယ်',
            'ဥကတ' => 'တောင်ဉက္ကလာပမြို့နယ်',
            'တကန' => 'တိုက်ကြီးမြို့နယ်',
            'တမန' => 'တာမွေမြို့နယ်',
            'သကတ' => 'သာကေတမြို့နယ်',
            'သလန' => 'သန်လျင်မြို့နယ်',
            'သဃက' => 'သင်္ဃန်းကျွန်းမြို့နယ်',
            'သခန' => 'သုံးခွမြို့နယ်',
            'တတန' => 'တွံတေးမြို့နယ်',
            'ရကန' => 'ရန်ကင်းမြို့နယ်',
        ],

        '13' => [
            'AKhaNa' => 'Aikechan Township',
            'HaTaNa' => 'Hotaung Township',
            'HaPaNa' => 'Hopang Township',
            'ThaNaNa' => 'Theinni Township',
            'HsaHsaNa' => 'Hsi Hseng Township',
            'ThaPaNa' => 'Hsipaw Township',
            'KaLaNa' => 'Kalaw Township',
            'KaTaNa' => 'Kyinetone Township',
            'KaKaNa' => 'Konkyan Township',
            'KaHaNa' => 'Kunhing Township',
            'KaKhaNa' => 'Kutkai Township',
            'KaMaNa' => 'Kyaukme Township',
            'KaThaNa' => 'Kyethi Township',
            'LaKhaNa' => 'Linkhay Township',
            'LaRaNa' => 'Lashio Township',
            'LaKaNa' => 'Laukkaing Township',
            'RaSaNa' => 'Yetsaut Township',
            'LaLaNa' => 'Loilem Township',
            'MaBaNa' => 'Mabein Township',
            'MaTaNa' => 'Mantong Township',
            'MaHsaNa' => 'Mong Hsat Township',
            'MaRaNa' => 'Mong Hsu Township',
            'MaHpaNa' => 'Mong Hpayak Township',
            'MaLaNa' => 'Mong Lar Township',
            'MaNaNa' => 'Mong Ne Township',
            'MaPaNa' => 'Mong Ping Township',
            'MaTaNa' => 'Mong Tone Township',
            'MaYaNa' => 'Mong Yang Township',
            'MaHsaTa' => 'Muse Township',
            'NaKhaNa' => 'Namhkam Township',
            'NaHsaNa' => 'Namhsan Township',
            'NaSaNa' => 'Nansang Township',
            'NaHpaNa' => 'Narhpan Township',
            'NaTaNa' => 'Nanttit Township',
            'NaMaTa' => 'Namtu Township',
            'NaKhaTa' => 'Naungcho Township',
            'NyaRaNa' => 'Nyaungshwe Township',
            'PaHsaNa' => 'Pansann Township',
            'PaWaNa' => 'Panwine Township',
            'HpaKhaNa' => 'Pekon Township',
            'PaTaYa' => 'Pindaya Township',
            'PaLaNa' => 'Pinlaung Township',
            'TaKhaLa' => 'Tachileik Township',
            'TaYaNa' => 'Tangyan Township',
            'TaKaNa' => 'Taunggyi Township',
            'RaNgaNa' => 'Ywangan Township',
            'MaNaTa' => 'Mong Nai Township',
            'MaKhaTa' => 'Mong Koak Township',
        ],

        '၁၃' => [
            'အခန' => 'အိုက်ချန်မြို့နယ်',
            'ဟတန' => 'ဟိုတောင်းမြို့နယ်',
            'ဟပန' => 'ဟိုပန်မြို့နယ်',
            'သနန' => 'သိန္နီမြို့နယ်',
            'ဆဆန' => 'ဆီဆိုင်မြို့နယ်',
            'သပန' => 'သီပေါမြို့နယ်',
            'ကလန' => 'ကလောမြို့နယ်',
            'ကတန' => 'ကျိုင်းတုံမြို့နယ်',
            'ကကန' => 'ကုန်းကြမ်းမြို့နယ်',
            'ကဟန' => 'ကွန်ဟိန်းမြို့နယ်',
            'ကခန' => 'ကွတ်ခိုင်မြို့နယ်',
            'ကမန' => 'ကျောက်မဲမြို့နယ်',
            'ကသန' => 'ကျေးသီးမြို့နယ်',
            'လခန' => 'လင်းခေးမြို့နယ်',
            'လရန' => 'လားရှိုးမြို့နယ်',
            'လကန' => 'လောက်ကိုင်မြို့နယ်',
            'ရစန' => 'ရပ်စောက်မြို့နယ်',
            'လလန' => 'လွိုင်လင်မြို့နယ်',
            'မဘန' => 'မဘိမ်းမြို့နယ်',
            'မတန' => 'မန်တုံမြို့နယ်',
            'မဆန' => 'မိုင်းဆတ်မြို့နယ်',
            'မရန' => 'မိုင်းရှုးမြို့နယ်',
            'မဖန' => 'မိုင်းဖြတ်မြို့နယ်',
            'မလန' => 'မိုင်းလားမြို့နယ်',
            'မနန' => 'မိုင်းနဲမြို့နယ်',
            'မပန' => 'မိုင်းပြင်းမြို့နယ်',
            'မတန' => 'မိုင်းတုံမြို့နယ်',
            'မယန' => 'မိုင်းယန်းမြို့နယ်',
            'မဆတ' => 'မူဆယ်မြို့နယ်',
            'နခန' => 'နမ့်ခမ်းမြို့နယ်',
            'နဆန' => 'နမ့်ဆန်မြို့နယ်',
            'နစန' => 'နမ့်စန်မြို့နယ်',
            'နဖန' => 'နားဖန်မြို့နယ်',
            'နတန' => 'နမ့်တစ်မြို့နယ်',
            'နမတ' => 'နမ္မတူမြို့နယ်',
            'နခတ' => 'နောင်ချိုမြို့နယ်',
            'ညရန' => 'ညောင်ရွှေမြို့နယ်',
            'ပဆန' => 'ပန်ဆန်းမြို့နယ်',
            'ပဝန' => 'ပန်ဝိုင်မြို့နယ်',
            'ဖခန' => 'ဖယ်ခုံမြို့နယ်',
            'ပတယ' => 'ပင်းတယမြို့နယ်',
            'ပလန' => 'ပင်လောင်းမြို့နယ်',
            'တခလ' => 'တာချီလိတ်မြို့နယ်',
            'တယန' => 'တန့်ယန်းမြို့နယ်',
            'တကန' => 'တောင်ကြီးမြို့နယ်',
            'ရငန' => 'ရွာငံမြို့နယ်',
            'မနတ' => 'မိုင်းနောင်မြို့နယ်',
            'မခတ' => 'မိုင်းခုတ်မြို့နယ်',
        ],

        '14' => [
            'BaKaLa' => 'Bogale Township',
            'DaNaHpa' => 'Danubyu Township',
            'DaDaRa' => 'Dedaye Township',
            'HaThaTa' => 'Hinthada Township',
            'AGaPa' => 'Ingapu Township',
            'KaKaHta' => 'Kangyidaunt Township',
            'KaLaNa' => 'Kyaiklat Township',
            'KaKhaNa' => 'Kyangin Township',
            'KaKaNa' => 'Kyaunggon Township',
            'KaPaNa' => 'Kyopyaw Township',
            'LaPaTa' => 'Labutta Township',
            'LaMaNa' => 'Lemyethna Township',
            'MaAPa' => 'Ma-ubin Township',
            'MaMaKa' => 'Mawlamyinegyun Township',
            'MaANa' => 'Myanaung Township',
            'MaMaNa' => 'Myaungmya Township',
            'NgaPaTa' => 'Ngapudaw Township',
            'NyaTaNa' => 'Nyaungdon Township',
            'PaTaNa' => 'Pantanaw Township',
            'PaThaNa' => 'Pathein Township',
            'HpaPaNa' => 'Pyapon Township',
            'ThaPaNa' => 'Thabaung Township',
            'WaKhaMa' => 'Wakema Township',
            'RaKaNa' => 'Yegyi Township',
            'ZaLaNa' => 'Zalun Township',
            'NgaHsaNa' => 'Ngwesaung Township',
            'HaKaKa' => 'Hainggyikyun Township',
            'RaThaYa' => 'Shwethaungyan Township',
        ],

        '၁၄' => [
            'ဘကလ' => 'ဘိုကလေးမြို့နယ်',
            'ဓနဖ' => 'ဓနုဖြူမြို့နယ်',
            'ဒဒရ' => 'ဒေးဒရဲမြို့နယ်',
            'ဟသတ' => 'ဟင်္သာတမြို့နယ်',
            'အဂပ' => 'အင်္ဂပူမြို့နယ်',
            'ကကထ' => 'ကန်ကြီးထောင့်မြို့နယ်',
            'ကလန' => 'ကျိုက်လတ်မြို့နယ်',
            'ကခန' => 'ကြံခင်းမြို့နယ်',
            'ကကန' => 'ကျောင်းကုန်းမြို့နယ်',
            'ကပန' => 'ကျုံပျော်မြို့နယ်',
            'လပတ' => 'လပွတ္တာမြို့နယ်',
            'လမန' => 'လေးမျက်နှာမြို့နယ်',
            'မအပ' => 'မအူပင်မြို့နယ်',
            'မမက' => 'မော်လမြိုင်ကျွန်းမြို့နယ်',
            'မအန' => 'မြန်အောင်မြို့နယ်',
            'မမန' => 'မြောင်းမြမြို့နယ်',
            'ငပတ' => 'ငပုတောမြို့နယ်',
            'ညတန' => 'ညောင်တုန်းမြို့နယ်',
            'ပတန' => 'ပန်းတနော်မြို့နယ်',
            'ပသန' => 'ပုသိမ်မြို့နယ်',
            'ဖပန' => 'ဖျာပုံမြို့နယ်',
            'သပန' => 'သာပေါင်းမြို့နယ်',
            'ဝခမ' => 'ဝါးခယ်မမြို့နယ်',
            'ရကန' => 'ရေကြည်မြို့နယ်',
            'ဇလန' => 'ဇလွန်မြို့နယ်',
            'ငဆန' => 'ငွေဆောင်မြို့နယ်',
            'ဟကက' => 'ဟိုင်းကြီးကျွန်းမြို့နယ်',
            'ရသယ' => 'ရွှေသောင်ယံမြို့နယ်',
        ],
    ],
];
